#!/bin/sh

#archs = (amd64, 386, arm64, arm)

date=$(date +%d.%m.%y-%H:%M:%S)

# Build AMD64
arch=amd64
GOOS=linux GOARCH=$arch go build -o "dist/linux/$arch/expr_"$arch"_$date.exe"
GOOS=windows GOARCH=$arch go build -o "dist/windows/$arch/expr_"$arch"_$date.exe"
GOOS=darwin GOARCH=$arch go build -o "dist/osx/$arch/expr_"$arch"_$date.exe"

# Build x86
arch=386
GOOS=linux GOARCH=$arch go build -o "dist/linux/$arch/expr_"$arch"_$date.exe"
GOOS=windows GOARCH=$arch go build -o "dist/windows/$arch/expr_"$arch"_$date.exe"
GOOS=darwin GOARCH=$arch go build -o "dist/osx/$arch/expr_"$arch"_$date.exe"

# Build arm
#arch=arm
GOOS=linux GOARCH=$arch go build -o "dist/linux/$arch/expr_"$arch"_$date.exe"
#GOOS=darwin GOARCH=$arch go build -o "dist/osx/$arch/expr_"$arch"_$date.exe"

# Build arm64
arch=arm64
GOOS=linux GOARCH=$arch go build -o "dist/linux/$arch/expr_"$arch"_$date.exe"
#GOOS=darwin GOARCH=$arch go build -o "dist/osx/$arch/expr_"$arch"_$date.exe"
