<Program>             =  <Block>     ;
<Block>               =  "{" Statement+ "}" | <XMLTree>  ;
<Statement>           =  <ExpressStatement> ;
<ExpressStatement>    =  ( <Declaration> | <Loop> ) ;
<Declaration>         =  <ExpressDeclaration> ;
<ExpressDeclaration>  =  <Type> <Ident> <AssignmentOp> <Expression> ;
<Type>                =  "int" ;
<Ident>               =  <IDENTIFIER_NAME> ;
<AssignmentOp>        =  "=" ;
<Expression>          =  { <Term> <ExprOp> }+ ;
<ExprOp>              =  ( "+" | "-" ) ;
<Term>                =  { <Factor> <TermOp> }+ ;
<TermOp>              =  ( "*" | "/" ) ;
<Factor>              =  ( <Literal> | <Ident> | "" <Expression> ")" ) ;
<Literal>             =  ( <INTEGER> | <Object> ) ;
<Object>              =  <Block> ;
<Loop>                =  <ForLoop> ;
<ForLoop>             =  "for" <ExpressDeclaration> <Expression> <Expression> <Block> ;
<ForInLoop>           =  "for" <Ident> "in" <Iterable> <Block> ;
<ForOfLoop>           =  "for" <Ident> "of" <Iterable> <Block> ;
<ForEverLoop>         =  "for" <Block> ;
<WhileLoop>           =  "while" <Expression> <Block> ;
<DoWhileLoop>         =  "do" <Block> <Expression> "while" <Expression> ;